#!/usr/bin/env python

import sys

from ipykernel import kernelapp
from notebook.notebookapp import NotebookApp

if __name__ == '__main__':
    if len(sys.argv) > 2 and sys.argv[1] == '-m' and sys.argv[2] == 'ipykernel':
        kernelapp.launch_new_instance()
    elif len(sys.argv) > 1 and sys.argv[1] == 'serve':
        sys.argv = [sys.argv[0]]
        app = NotebookApp()
        app.open_browser = False
        app.initialize()
        app.start()
    else:
        print('Unknown arguments: {}'.format(sys.argv[1:]))
        
